-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color4 = '#AAC1F0'
local Color8 = '#1B1A29'
local Color0 = '#576A8F'
local Color9 = '#2d2d3e'
local Color10 = '#2f2734'
local Color1 = '#CCDDFF'
local Color11 = '#32384f'
local Color3 = '#F0AAAC'
local Color5 = '#AFAAF0'
local Color6 = '#9AD0E6'
local Color2 = '#AADCF0'
local Color7 = '#FFFFFF'
local Color12 = '#657AA3'

highlight('Comment', nil, Color0, 'italic')
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Operator', nil, Color4, nil)
highlight('Function', nil, Color5, 'italic')
highlight('Type', nil, Color6, 'italic')
highlight('StatusLine', Color7, Color8, nil)
highlight('WildMenu', Color8, Color7, nil)
highlight('Pmenu', Color8, Color7, nil)
highlight('PmenuSel', Color7, Color8, nil)
highlight('PmenuThumb', Color8, Color7, nil)
highlight('DiffAdd', Color9, nil, nil)
highlight('DiffDelete', Color10, nil, nil)
highlight('Normal', Color8, Color7, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color8, Color0, nil)
highlight('TabLineSel', Color3, Color8, nil)
highlight('TabLineFill', Color8, Color0, nil)
highlight('TSPunctDelimiter', nil, Color7, nil)

link('TSFunction', 'Function')
link('TSNamespace', 'TSType')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Whitespace', 'Comment')
link('TSOperator', 'Operator')
link('TSNumber', 'Number')
link('TSConstant', 'Constant')
link('TSPunctBracket', 'MyTag')
link('TSLabel', 'Type')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSProperty', 'TSField')
link('TSType', 'Type')
link('TSKeyword', 'Keyword')
link('Folded', 'Comment')
link('TSFuncMacro', 'Macro')
link('Conditional', 'Operator')
link('TSTagDelimiter', 'Type')
link('TelescopeNormal', 'Normal')
link('TSParameterReference', 'TSParameter')
link('TSConditional', 'Conditional')
link('TSString', 'String')
link('Macro', 'Function')
link('TSField', 'Constant')
link('TSFloat', 'Number')
link('TSComment', 'Comment')
link('CursorLineNr', 'Identifier')
link('NonText', 'Comment')
link('TSParameter', 'Constant')
link('TSRepeat', 'Repeat')
link('Repeat', 'Conditional')
link('TSTag', 'MyTag')
link('Operator', 'Keyword')
